<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="../lib/jquery.js"></script>
</head>
<body>

</body>
<script>
    function getData(url, data = {}){ // data = {} 如果data 没有传值，那么data的值就是{}
        return new Promise((resolve, reject) => {
            $.ajax({
                type: 'GET',
                url: url,
                dataType: 'json',
                data: data,
                success: function (res) {
                    resolve(res); // 这里必须要调用 resolve 或者 reject 来改变 promise 的 对象, 否则, 它不会执行后面then 的方法
                },
                error: function (res) {
                    reject(res); // 同理也是一样，这里的reject 和 resolve 必须调用一个
                }
            })
        });
    }
    const p = getData('id.json').then((res) =>{
        const {id} = res;
        console.log('{id}', {id});
        console.log('id', id);
        return getData('username.json', {id});
        // return 'te'
    }).then((res) => { // 这个res 是上面那个 then return 后面的值, 但是上面那个 getData('username.json', {id}) 是个promise 对象, 所以res 是这个promise对象的resolve参数
        console.log(res);
        const {username} = res;
        console.log('{username}', {username});
        console.log('username', username);
        return getData('email.json', {username});
    }).then((res) => {
        console.log('res', res);
        return res;
    });
    console.log(p);

    const pro1 = new Promise((resolve, reject) => {
        resolve('success');
    }).then((res) => {
        console.log(res);
        return 'success again';
    }).then((res) => {
        console.log(res);
        return 'success again and again';
    }).then((res) => {
        return res;
    });



</script>
</html>